[package]
edition = "2021"
name = "pre-plus-plus"
version = "0.1.0"

[dependencies]
clap = {version = "3.2.16", features = ["derive"]}
serde = {version = "1.0.143", features = ["derive"]}
toml = "0.5.9"
regex = "1.5"