[project]
name = "pre++"
version = "1.0.0"
edition = "2022"
include = "include"
src = "src/main.cpp"
standard = "17"

[dependencies] # as of right now, dosent work with cppm, but should be a futrue feature.
fmt = "https://github.com/fmtlib/fmt"
spinners = "https://github.com/jkuri/spinners"
tomlplusplus = "https://github.com/marzer/tomlplusplus/"
Custos = "https://github.com/codewithrodi/Custos"